# Numpy

In [116]:
"hello world"

'hello world'

In [117]:
# shift + enter

In [118]:
#! pip install numpy

In [119]:
import numpy as np

In [120]:
l = [1,2, 3, 5, 4, 5, 6]

In [121]:
l*2

[1, 2, 3, 5, 4, 5, 6, 1, 2, 3, 5, 4, 5, 6]

In [122]:
type(l)

list

In [123]:
a1 = np.array(l)

In [124]:
a1

array([1, 2, 3, 5, 4, 5, 6])

In [125]:
type(a1)

numpy.ndarray

In [126]:
a1.ndim

1

In [127]:
a1.shape

(7,)

In [128]:
a = np.array([[1,2, 3, 8],
              [4, 5,6, 9]])

In [129]:
a

array([[1, 2, 3, 8],
       [4, 5, 6, 9]])

In [130]:
a.ndim

2

In [131]:
a.shape

(2, 4)

In [132]:
b = np.array([[[1,2, 3, 8],
              [4, 5,6, 9]],
             [[1,2, 3, 8],
              [4, 5,6, 9]],
             [[1,2, 3, 8],
              [4, 5,6, 9]]])

In [133]:
b

array([[[1, 2, 3, 8],
        [4, 5, 6, 9]],

       [[1, 2, 3, 8],
        [4, 5, 6, 9]],

       [[1, 2, 3, 8],
        [4, 5, 6, 9]]])

In [134]:
b.ndim

3

In [135]:
b.shape

(3, 2, 4)

In [136]:
b.dtype

dtype('int32')

In [137]:
a = np.ones((2,3,5), dtype='bool')

In [138]:
a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [139]:
a.ndim

3

In [140]:
a.dtype

dtype('bool')

In [141]:
b = np.zeros((3, 4))

In [142]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
m = np.arange(1, 101)
m

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [144]:
m.ndim

1

In [145]:
m.reshape((5, 5, 4))

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [146]:
b = np.arange(1, 10).reshape(3, 3)

In [147]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
b = np.arange(1, 10).reshape(1, 3, 3)

In [149]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [150]:
np.linspace(1, 100, num=20, endpoint=False, dtype='bool')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [151]:
len(np.linspace(1, 100))

50

In [152]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [153]:
b.ndim

3

In [154]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
b.flatten(order='f')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [156]:
a =  np.arange(1, 16).reshape(3, 5)

In [157]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [158]:
np.arange(1, 16).reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [159]:
np.arange(1, 16).reshape(15, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [160]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [161]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [162]:
np.transpose(a)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [163]:
b = np.arange(1, 25).reshape(2, 4, 3)

In [164]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [165]:
b.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [166]:
b.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [167]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(1, 10).reshape(3, 3)

In [168]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [171]:
a - b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [172]:
np.add(a, b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [173]:
 np.subtract(a, b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [174]:
 np.divide(a, b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [175]:
 np.multiply(a, b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [176]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
a.min(axis=0)

array([1, 2, 3])

In [178]:
a.max(axis=0)

array([7, 8, 9])

In [179]:
a.min(axis=1)

array([1, 4, 7])

In [180]:
a.max(axis=1)

array([3, 6, 9])

In [181]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
np.sum(a)

45

In [183]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [184]:
np.argmax(a, axis=1)

array([2, 2, 2], dtype=int64)

In [185]:
np.argmin(a, axis=0)

array([0, 0, 0], dtype=int64)

In [186]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [187]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [188]:
np.sum(a, axis=0)

array([12, 15, 18])

In [189]:
np.trace(a)

15

In [190]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [191]:
np.mean(a)

5.0

In [192]:
np.median(a)

5.0

In [193]:
np.std(a)

2.581988897471611

In [194]:
np.var(a)

6.666666666666667

In [195]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [196]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [197]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [198]:
a = np.arange(1, 101).reshape(10, 10)

In [199]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [200]:
a[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [201]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [202]:
a[3:6, 3]

array([34, 44, 54])

In [203]:
a[3:6, 3:6]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56]])

In [204]:
a[3:10:2, 3:8:2]

array([[34, 36, 38],
       [54, 56, 58],
       [74, 76, 78],
       [94, 96, 98]])

In [205]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [206]:
a[:,3]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [207]:
a[:3,3]

array([ 4, 14, 24])

In [208]:
a[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [209]:
a[:,3:10:2]

array([[  4,   6,   8,  10],
       [ 14,  16,  18,  20],
       [ 24,  26,  28,  30],
       [ 34,  36,  38,  40],
       [ 44,  46,  48,  50],
       [ 54,  56,  58,  60],
       [ 64,  66,  68,  70],
       [ 74,  76,  78,  80],
       [ 84,  86,  88,  90],
       [ 94,  96,  98, 100]])

In [210]:
t = {1, 2, 3, 4, 5}

In [211]:
d = {"key": "value", "name": "johan"}

In [212]:
np.array(d)

array({'key': 'value', 'name': 'johan'}, dtype=object)

In [213]:
a = np.array([1, 2, 3, 4])


In [214]:
a

array([1, 2, 3, 4])

In [215]:
list(a)

[1, 2, 3, 4]

In [216]:
tuple(a)

(1, 2, 3, 4)

In [217]:
set(a)

{1, 2, 3, 4}

In [218]:
str(a)

'[1 2 3 4]'

In [219]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(1, 10).reshape(3, 3)

In [220]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [221]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [222]:
np.dot(a, b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [223]:
np.multiply(a, b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# concatanation

In [224]:
a = np.arange(1, 17).reshape(4, 4)
b = np.arange(17, 33).reshape(4, 4)

In [225]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [226]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [228]:
np.concatenate((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [229]:
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [231]:
np.hstack((a, b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [232]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [233]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [237]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [239]:
np.split(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [240]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [243]:
np.split(a,2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [244]:
np.split(a,4, axis=1)


[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [248]:
s = np.array([11, 22, 33, 44, 55, 66, 77, 88])

In [249]:
s

array([11, 22, 33, 44, 55, 66, 77, 88])

In [250]:
np.split(s,[2])

[array([11, 22]), array([33, 44, 55, 66, 77, 88])]

In [251]:
np.split(s,[3])

[array([11, 22, 33]), array([44, 55, 66, 77, 88])]

In [252]:
s

array([11, 22, 33, 44, 55, 66, 77, 88])

In [253]:
np.split(s,[3,7])

[array([11, 22, 33]), array([44, 55, 66, 77]), array([88])]

In [254]:
s

array([11, 22, 33, 44, 55, 66, 77, 88])

In [255]:
np.split(s,[3,4])

[array([11, 22, 33]), array([44]), array([55, 66, 77, 88])]

In [262]:
np.random.random()

0.9223410154264274

In [268]:
np.random.random(5)

array([0.85301602, 0.67966481, 0.74387028, 0.33935918, 0.58667176])

In [265]:
from random import *

In [266]:
random()

0.7888278276348598

In [270]:
np.random.random((3,5))

array([[0.66613533, 0.58206505, 0.29616735, 0.28587688, 0.68847947],
       [0.73116289, 0.42132539, 0.85851085, 0.89018192, 0.95813382],
       [0.97624183, 0.5237585 , 0.92593302, 0.44506091, 0.81908502]])

In [271]:
np.random.random((1,3,5))

array([[[0.45154525, 0.33137608, 0.50835342, 0.01831131, 0.76543037],
        [0.96680596, 0.82446183, 0.60867731, 0.54646159, 0.66631294],
        [0.54424176, 0.97293011, 0.88993915, 0.25558687, 0.32312756]]])

In [272]:
np.random.random((2,3,5))

array([[[0.76983996, 0.54023434, 0.98689982, 0.89711748, 0.08170731],
        [0.19684192, 0.35854412, 0.74808492, 0.21544231, 0.91449052],
        [0.07313277, 0.8332641 , 0.36345215, 0.5857334 , 0.22687895]],

       [[0.0616352 , 0.95490199, 0.71790331, 0.40892169, 0.45173046],
        [0.12143362, 0.07584515, 0.55944742, 0.04617273, 0.30863631],
        [0.33508539, 0.57832059, 0.82257926, 0.81449439, 0.38798694]]])

In [283]:
np.random.randint(15,size=(2, 4))

array([[ 8,  6,  7,  5],
       [14, 13,  4, 14]])

In [284]:
np.random.randint(15,size=(2, 4, 4))

array([[[ 9,  4,  7,  9],
        [ 4,  9,  3,  9],
        [ 3,  8,  1,  8],
        [ 8,  2,  4,  2]],

       [[14, 13,  2, 13],
        [11,  0,  3, 14],
        [ 8,  2,  0, 11],
        [ 3,  7,  1,  1]]])

In [289]:
a = np.linspace(1, 15, 25)

In [290]:
a

array([ 1.        ,  1.58333333,  2.16666667,  2.75      ,  3.33333333,
        3.91666667,  4.5       ,  5.08333333,  5.66666667,  6.25      ,
        6.83333333,  7.41666667,  8.        ,  8.58333333,  9.16666667,
        9.75      , 10.33333333, 10.91666667, 11.5       , 12.08333333,
       12.66666667, 13.25      , 13.83333333, 14.41666667, 15.        ])

In [291]:
np.random.choice(a)

6.25

In [292]:
np.random.uniform(1, 100, 250)

array([48.66743668, 68.02456413, 47.75160215, 35.58090392, 68.78650761,
       33.66491217, 17.90024052, 52.34651465, 23.13061618, 90.43273272,
       77.36282693, 86.99251194, 37.49889593, 81.05198292, 97.45651153,
       36.63057531, 73.53369694, 67.91906643, 74.01425113, 24.61320347,
       64.84207426, 22.03793658, 38.52473752, 25.27218462, 79.637706  ,
       73.29643207, 46.46164441, 35.49233932, 96.54816255,  8.48745558,
       68.46686245, 45.25347739,  2.36632539, 67.19675915, 20.36353508,
        2.86570284, 84.78560069, 27.9804424 , 95.17573451, 24.33519004,
        1.24402442, 41.08806114, 71.80155998, 62.73710755, 96.06805436,
       69.82687993, 17.81831541, 93.67363714, 28.61190602, 95.4629597 ,
       16.58142926, 24.58273005, 27.10018777, 86.95742043, 92.084529  ,
       97.97045792, 32.92026785, 86.3785731 , 44.6501657 , 99.87982344,
       26.60308817, 19.86182542, 83.87117497, 70.29300308, 17.99851859,
       77.63342928, 32.85854412,  1.24626904, 28.29458111, 40.02

In [293]:
np.random.uniform(20, 5, 100)

array([ 8.16956407, 18.16228221, 14.73898228, 15.33085457, 17.8284925 ,
       13.1996792 ,  5.79889154,  5.5946293 , 17.54636388, 10.73482138,
       12.47066707,  6.00279827, 11.25345135, 18.61043122, 13.61821051,
       13.44284714, 17.02995955, 12.06969905, 16.99189915, 14.05781317,
        7.92575447, 12.89003455, 16.39402662,  9.04535226,  6.6210275 ,
       11.64669119, 17.86362733, 16.37518731, 12.01100829,  6.64763513,
        8.8042474 , 11.49323678,  6.88865735, 12.23572456, 13.54203085,
        9.40137623, 14.31104977, 15.59064798,  6.48659106, 12.02394413,
       12.25085842, 15.25200687, 17.07010295, 19.36093435, 14.04899517,
       13.88359392, 16.00676196,  6.89860372,  7.97647761,  7.85575476,
       11.15160956, 15.22627826,  9.14065109, 17.10147626, 12.5363155 ,
       15.35133495,  5.42250791, 19.15033498,  9.78031389, 19.9682542 ,
        6.74068878,  9.19394681, 15.98662086, 16.77737231,  5.32540782,
       14.10667516, 11.07081429,  6.28740398, 17.00976797,  6.69

In [294]:
len(np.random.uniform(20, 5, 100))

100

In [296]:
s = "Hello"
s1 = "world"

In [297]:
s +s1

'Helloworld'

In [298]:
np.char.add(s,s1)

array('Helloworld', dtype='<U10')

In [299]:
np.char.upper(s)

array('HELLO', dtype='<U5')

In [302]:
np.char.center(s, 20, ' ')

array('       Hello        ', dtype='<U20')